apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kserve
  namespace: flux-system
spec:
    values: 
      kserve:
        controller:
          deploymentMode: RawDeployment
          gateway:
            ingressGateway:
              enableGatewayApi: true
              kserveGateway: default/ai-gateway