apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-gpu-operator
  namespace: flux-system
spec:
  values:
    operator:
      runtimeClass: nvidia-container-runtime
    mig:
      strategy: single