apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-dynamo
  namespace: flux-system
spec:
  chart:
    spec:
      version: "0.6.0"
  values:
    dynamo-operator:
      enabled: true